### API Status Check
GET {{BASE_URL}}/
Content-Type: application/json

### Armando Constanza
GET {{BASE_URL}}/armando
Content-Type: application/json

### Arnoldi
GET {{BASE_URL}}/arnoldi
Content-Type: application/json

### Bounos
GET {{BASE_URL}}/bounos
Content-Type: application/json

### Mallemacci
GET {{BASE_URL}}/mallemacci
Content-Type: application/json

### Salcovsky
GET {{BASE_URL}}/salcovsky
Content-Type: application/json

### Surwal
GET {{BASE_URL}}/surwal
Content-Type: application/json

### ZZ Deptos
GET {{BASE_URL}}/zz
Content-Type: application/json

### LG Inmobiliaria
GET {{BASE_URL}}/lginmobiliaria
Content-Type: application/json
### Raquel Inmobiliaria
GET {{BASE_URL}}/raquelinmobiliaria
Content-Type: application/json

### ECA Propiedades
GET {{BASE_URL}}/ecapropiedades
Content-Type: application/json

### Zuchelli
GET {{BASE_URL}}/zuchelli
Content-Type: application/json

### Crear nuevo Scraper (ECA Propiedades)
POST {{BASE_URL}}/scrapers
Content-Type: application/json

{
  "name": "Zuchelli",
  "url": "https://zuchelihermanos.com/operaciones-propiedad/alquiler/",
  "selector": ".property-item.clearfix",
  "mappings": {
        "title": "h4 > a",
    "location": ".detail > p",
    "price": "h5.price",
    "imgUrl": ".attachment-property-thumb-image.size-property-thumb-image.wp-post-image",
    "url": "a.more-details",
    "company": "Zuchelli"
  }
}

### LG Inmobiliaria (con paginación)
POST {{BASE_URL}}/scrapers
Content-Type: application/json

{
  "name": "LGInmobiliaria",
  "url": "https://lginmobiliaria.com.ar/propiedades-encontradas/?status=alquiler",
  "selector": "article.property-item",
  "mappings": {
    "title": "h4 > a",
    "location": ".detail > p",
    "price": "h5.price",
    "imgUrl": ".attachment-property-thumb-image.size-property-thumb-image.wp-post-image",
    "url": "a.more-details"
  },
  "pagination": {
    "enabled": true,
    "type": "url",
    "selector": ".pagination.rh_pagination_classic a.real-btn",
    "urlTemplate": "https://lginmobiliaria.com.ar/propiedades-encontradas/page/{{PAGE}}/?status=alquiler",
    "maxPages": 5
  }
}

