### API Status Check
GET {{BASE_URL}}/
Content-Type: application/json

### Armando Constanza
GET {{BASE_URL}}/armando
Content-Type: application/json

### Arnoldi
GET {{BASE_URL}}/arnoldi
Content-Type: application/json

### Bounos
GET {{BASE_URL}}/bounos
Content-Type: application/json

### Mallemacci
GET {{BASE_URL}}/mallemacci
Content-Type: application/json

### Salcovsky
GET {{BASE_URL}}/salcovsky
Content-Type: application/json

### Surwal
GET {{BASE_URL}}/surwal
Content-Type: application/json

### ZZ Deptos
GET {{BASE_URL}}/zz
Content-Type: application/json

### LG Inmobiliaria
GET {{BASE_URL}}/lginmobiliaria
Content-Type: application/json
### Raquel Inmobiliaria
GET {{BASE_URL}}/raquelinmobiliaria
Content-Type: application/json

### ECA Propiedades
GET {{BASE_URL}}/ecapropiedades
Content-Type: application/json

### Zuchelli
GET {{BASE_URL}}/zuchelli
Content-Type: application/json


### TestScraper
GET {{BASE_URL}}/testscraper
Content-Type: application/json

### NewScraperTest
GET {{BASE_URL}}/newscrapertest
Content-Type: application/json

### UnoPropiedades
GET {{BASE_URL}}/unopropiedades
Content-Type: application/json



