
### Crear nuevo Scraper (ECA Propiedades)
POST {{BASE_URL}}/scrapers
Content-Type: application/json

{
  "name": "BounosPropiedades",
  "url": "https://bounospropiedades.com.ar/propiedades/?tipo=Alquiler",
  "selector": "article.propiedades__item",
  "mappings": {
    "title": ".propiedades__location__address",
    "location": ".propiedades__location__address",
    "price": ".propiedades__location__address",
    "imgUrl": ".relative img",
    "url": ".propiedades__files a",
    "company": ""
  }
}

### LG Inmobiliaria (con paginación)
POST {{BASE_URL}}/scrapers
Content-Type: application/json

{
  "name": "BounosPropiedades",
  "url": "https://bounospropiedades.com.ar/propiedades/?tipo=Alquiler",
  "selector": "article.propiedades__item",
  "mappings": {
    "title": ".propiedades__location__address",
    "location": ".propiedades__location__address",
    "price": ".propiedades__location__address",
    "imgUrl": ".relative img",
    "url": ".propiedades__files a",
    "company": "Bounos Propiedades"
  },
  "pagination": {
    "enabled": true,
    "type": "url",
    "selector": ".pagination__item a",
    "urlTemplate": "https://bounospropiedades.com.ar/propiedades/{{PAGE}}?tipo=Alquiler",
    "maxPages": 3,
    "nextButtonSelector": ""
  }
}
